### ISSUE TITLE
npm availability

### ISSUE THREAD

**Issue by stachu3478** [screepers/utf15#4]
Hello, I use npm in my codebase with Typescript and i'm not able to maintain the utf15 script without lot of changes in that i would like to skip. I think adding such `package.json` would be a nice approach:
```
{
  "name": "utf15",
  "version": "1.0.0",
  "description": "",
  "main": "utf15.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/screepers/utf15.git"
  },
  "author": "screepers",
  "license": "MIT"
}
```

**Comment by Mototroller** [comment]
Hi @stachu3478! Thanks, good point, feel free to create a PR with such a template, I'll check and modify "description", "author" and "name" (since packet name "utf15" is too short and confusing, smth like "screeps-utf15" will be better), then I'll merge it.

Personally I don't use Typescript and package manager for small libs, but suggestion sounds nice, why not.

**Comment by stachu3478** [comment]
Here it is! https://github.com/screepers/utf15/pull/5

**Comment by Mototroller** [comment]
https://www.npmjs.com/package/screeps-utf15
@stachu3478, thanks!
